Repository SecondBrainPlanner/SecondBrain, pull requests merged in 2024-07, with the labels that each got.

#3 Update activity_main.xml
  app/src/main/res/layout/activity_main.xml
Labels: enhancement

#7 4 add button press action add item UI
  app/build.gradle.kts
  app/src/main/java/io/github/secondbrainplanner/MainActivity.java
  app/src/main/java/io/github/secondbrainplanner/NewTaskSheet.kt
  app/src/main/java/io/github/secondbrainplanner/TaskViewModel.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_new_task_sheet.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: enhancement, layout

#8 1 recycler view adapter
  app/src/main/java/io/github/secondbrainplanner/MainActivity.java
  app/src/main/java/io/github/secondbrainplanner/NewTaskSheet.kt
  app/src/main/java/io/github/secondbrainplanner/Task.java
  app/src/main/java/io/github/secondbrainplanner/TaskAdapter.java
  app/src/main/java/io/github/secondbrainplanner/TaskViewModel.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/item_task.xml
Labels: enhancement, layout

#11 6 database creation on device
  app/src/main/java/io/github/secondbrainplanner/DatabaseManager.java
  app/src/main/java/io/github/secondbrainplanner/TaskManager.java
Labels: enhancement

#13 12 database integration
  app/src/main/java/io/github/secondbrainplanner/MainActivity.java
  app/src/main/java/io/github/secondbrainplanner/NewTaskSheet.java
  app/src/main/java/io/github/secondbrainplanner/Task.java
  app/src/main/java/io/github/secondbrainplanner/TaskAdapter.java
  app/src/main/java/io/github/secondbrainplanner/TaskManager.java
  app/src/main/java/io/github/secondbrainplanner/TaskViewModel.java
  app/src/main/java/io/github/secondbrainplanner/TaskViewModelFactory.java
Labels: enhancement

#16 14 date sectioning in recycler view
  app/src/main/java/io/github/secondbrainplanner/TaskAdapter.java
  app/src/main/res/layout/item_task.xml
Labels: enhancement, layout

#18 Update Task.java
  app/src/main/java/io/github/secondbrainplanner/Task.java
Labels: bug

#20 19 integrate date picker in newtasksheet
  app/src/main/java/io/github/secondbrainplanner/NewTaskSheet.java
  app/src/main/res/layout/fragment_new_task_sheet.xml
Labels: enhancement

#21 15 recycler view shows future date sections
  app/src/main/java/io/github/secondbrainplanner/MainActivity.java
  app/src/main/java/io/github/secondbrainplanner/TaskAdapter.java
  app/src/main/java/io/github/secondbrainplanner/TaskViewModel.java
Labels: enhancement, layout

#24 23 show tasks older than 30 days
  app/src/main/java/io/github/secondbrainplanner/MainActivity.java
  app/src/main/java/io/github/secondbrainplanner/TaskAdapter.java
  app/src/main/java/io/github/secondbrainplanner/TaskViewModel.java
Labels: enhancement, layout

#29 26 design enhancement
  app/src/main/java/io/github/secondbrainplanner/MainActivity.java
  app/src/main/res/drawable/bottom_border.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/item_task.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: layout

#31 30 timestamp layout change on tasks
  app/src/main/java/io/github/secondbrainplanner/TaskAdapter.java
  app/src/main/java/io/github/secondbrainplanner/TaskViewModel.java
Labels: layout

#37 32 day of the week view
  app/src/main/java/io/github/secondbrainplanner/MainActivity.java
  app/src/main/java/io/github/secondbrainplanner/TaskAdapter.java
  app/src/main/res/layout/activity_main.xml
Labels: layout

#40 36 datepicker optimization
  app/src/main/java/io/github/secondbrainplanner/EditTaskSheet.java
  app/src/main/java/io/github/secondbrainplanner/NewTaskSheet.java
Labels: enhancement

#43 38 bottom sheets fragments full screen on launch
  app/src/main/java/io/github/secondbrainplanner/EditTaskSheet.java
  app/src/main/java/io/github/secondbrainplanner/NewTaskSheet.java
  app/src/main/res/values/styles.xml
Labels: bug

#45 month and year now appearing in the top left corner
  app/src/main/java/io/github/secondbrainplanner/MainActivity.java
  app/src/main/res/layout/activity_main.xml
Labels: enhancement, layout

#48 added numbers row under day of week row which is matching the current week day numbers
  app/src/main/java/io/github/secondbrainplanner/MainActivity.java
  app/src/main/res/layout/activity_main.xml
Labels: layout

#52 49 settings screen
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/github/secondbrainplanner/MainActivity.java
  app/src/main/java/io/github/secondbrainplanner/SettingsActivity.java
  app/src/main/res/drawable/settings.xml
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/menu/toolbar_menu.xml
Labels: enhancement

#53 34 export database to csv file
  app/src/main/java/io/github/secondbrainplanner/DatabaseManager.java
  app/src/main/java/io/github/secondbrainplanner/SettingsActivity.java
  app/src/main/res/layout/activity_settings.xml
Labels: enhancement

#55 added import func
  app/src/main/java/io/github/secondbrainplanner/DatabaseManager.java
  app/src/main/java/io/github/secondbrainplanner/SettingsActivity.java
Labels: enhancement

#57 added button date picker always shows selected date
  app/src/main/java/io/github/secondbrainplanner/MainActivity.java
  app/src/main/java/io/github/secondbrainplanner/NewTaskSheet.java
Labels: enhancement

#58 46 line under timestamp not showing on different resolution
  app/src/main/res/drawable/bottom_border.xml
  app/src/main/res/layout/item_task.xml
Labels: layout

#61 60 timestamp underline adjustment
  app/src/main/java/io/github/secondbrainplanner/MainActivity.java
  app/src/main/res/drawable/bottom_border.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/colors.xml
Labels: enhancement, layout

#62 33 complete tasks
  app/src/main/java/io/github/secondbrainplanner/TaskAdapter.java
  app/src/main/java/io/github/secondbrainplanner/TaskManager.java
  app/src/main/java/io/github/secondbrainplanner/TaskViewModel.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/item_task.xml
Labels: enhancement, layout

#65 App reset in settings
  app/src/main/java/io/github/secondbrainplanner/SettingsActivity.java
Labels: enhancement

#66 63 slight layout adjustments
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_edit_task_sheet.xml
  app/src/main/res/layout/fragment_new_task_sheet.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: layout

#71 67 screen for completed task
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/github/secondbrainplanner/CompletedTaskActivity.java
  app/src/main/java/io/github/secondbrainplanner/CompletedTaskAdapter.java
  app/src/main/java/io/github/secondbrainplanner/MainActivity.java
  app/src/main/java/io/github/secondbrainplanner/TaskAdapter.java
  app/src/main/java/io/github/secondbrainplanner/TaskManager.java
  app/src/main/java/io/github/secondbrainplanner/TaskViewModel.java
  app/src/main/res/drawable/check_box.xml
  app/src/main/res/layout/activity_completed_tasks.xml
  app/src/main/res/layout/item_completedtask.xml
  app/src/main/res/menu/toolbar_menu.xml
Labels: enhancement

#74 73 toolbar activities layout adjustment
  app/src/main/java/io/github/secondbrainplanner/CompletedTaskActivity.java
  app/src/main/java/io/github/secondbrainplanner/CompletedTaskAdapter.java
  app/src/main/res/layout/activity_completed_tasks.xml
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: layout

#78 updated toast & alert strings
  app/src/main/java/io/github/secondbrainplanner/MainActivity.java
  app/src/main/java/io/github/secondbrainplanner/SettingsActivity.java
  app/src/main/java/io/github/secondbrainplanner/TaskAdapter.java
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug

#79 76 mangegament for old tasks
  app/src/main/java/io/github/secondbrainplanner/TaskViewModel.java
Labels: enhancement

#82 75 task notifications
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/github/secondbrainplanner/AlarmHelper.java
  app/src/main/java/io/github/secondbrainplanner/AlarmReceiver.java
  app/src/main/java/io/github/secondbrainplanner/EditTaskSheet.java
  app/src/main/java/io/github/secondbrainplanner/MainActivity.java
  app/src/main/java/io/github/secondbrainplanner/NewTaskSheet.java
  app/src/main/java/io/github/secondbrainplanner/NotificationHelper.java
  app/src/main/java/io/github/secondbrainplanner/TaskViewModel.java
  app/src/main/java/io/github/secondbrainplanner/TaskViewModelFactory.java
  app/src/main/res/drawable/notification.xml
  app/src/main/res/layout/fragment_edit_task_sheet.xml
  app/src/main/res/layout/fragment_new_task_sheet.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#84 tasks of the past will now be highlighted in red
  app/src/main/java/io/github/secondbrainplanner/TaskAdapter.java
Labels: layout

#88 85 task show reminder time
  app/src/main/java/io/github/secondbrainplanner/TaskAdapter.java
  app/src/main/res/layout/item_task.xml
Labels: enhancement, layout

#90 general improvements
  app/src/main/java/io/github/secondbrainplanner/CompletedTaskAdapter.java
  app/src/main/java/io/github/secondbrainplanner/EditTaskSheet.java
  app/src/main/java/io/github/secondbrainplanner/NewTaskSheet.java
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#92 91 notification on uncomplete older tasks
  app/src/main/java/io/github/secondbrainplanner/CompletedTaskActivity.java
  app/src/main/java/io/github/secondbrainplanner/TaskViewModel.java
Labels: enhancement

#97 filter option
  app/src/main/java/io/github/secondbrainplanner/FilterTaskAdapter.java
  app/src/main/java/io/github/secondbrainplanner/MainActivity.java
  app/src/main/res/drawable/filter.xml
  app/src/main/res/menu/toolbar_menu.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#98 Saturday / Sunday are now bold instead of italic
  app/src/main/java/io/github/secondbrainplanner/TaskAdapter.java
  app/src/main/res/layout/item_task.xml
Labels: layout

#100 99 filter icon color bug
  app/src/main/java/io/github/secondbrainplanner/MainActivity.java
Labels: enhancement, layout
